#!/bin/bash

TMP_KUBE_EXE=$(mktemp)
curl -s https://raw.githubusercontent.com/colab-coop/kube/main/kube --output ${TMP_KUBE_EXE}
yes | cp -rf ${TMP_KUBE_EXE} /usr/local/bin/kube
rm -rf ${TMP_KUBE_EXE}
echo "Kube installed, you are ready to go..."
